# The below will look in Vault for /path/to/your/secret and will return the key 'secretkey'.
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-replacer-example-configmap
data:
  sample-secret: <secret:secret/data/test/demo~hello>